article:
    resource: "@ArticleBundle/Resources/config/routing.yml"
    prefix:   /

category:
    resource: "@CategoryBundle/Resources/config/routing.yml"
    prefix:   /

comments:
    resource: "@CommentsBundle/Resources/config/routing.yml"
    prefix:   /
user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
mainblog:
    path:  /mainblog/{_locale}
    defaults: { _controller:AppBundle:Main:index, _locale: "en"}
    requirements:
        _locale:  en|ar
mainblogdescription:
    path:  /mainblogdescription/{_locale}/{articleid}
    defaults: { _controller:AppBundle:Main:showdesc, _locale: "en"}
    requirements:
        _locale:  en|ar
catblog:
    path:  /catblog/{_locale}/{catid}
    defaults: { _controller:AppBundle:Main:showcatarticle, _locale: "en"}
    requirements:
        _locale:  en|ar		
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"	