UserBundle\Entity\user:
    type: entity
    table: user
    repositoryClass: UserBundle\Entity\userRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: '255'
        password:
            type: string
            length: '255'
        email:
            type: string
            length: '255'
        image:
            type: string
            length: '1000'
        facebook:
            type: string
            length: '255'
        twitter:
            type: string
            length: '255'
        googlePlus:
            type: string
            length: '255'
            column: google_plus
        linkedin:
            type: string
            length: '255'
        youtube:
            type: string
            length: '255'
    lifecycleCallbacks: {  }
