<?php

namespace Proxies\__CG__\CommentsBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class comments extends \CommentsBundle\Entity\comments implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'CommentsBundle\\Entity\\comments' . "\0" . 'id', '' . "\0" . 'CommentsBundle\\Entity\\comments' . "\0" . 'description', '' . "\0" . 'CommentsBundle\\Entity\\comments' . "\0" . 'authorname', '' . "\0" . 'CommentsBundle\\Entity\\comments' . "\0" . 'authoremail', '' . "\0" . 'CommentsBundle\\Entity\\comments' . "\0" . 'authorurl', '' . "\0" . 'CommentsBundle\\Entity\\comments' . "\0" . 'article_id');
        }

        return array('__isInitialized__', '' . "\0" . 'CommentsBundle\\Entity\\comments' . "\0" . 'id', '' . "\0" . 'CommentsBundle\\Entity\\comments' . "\0" . 'description', '' . "\0" . 'CommentsBundle\\Entity\\comments' . "\0" . 'authorname', '' . "\0" . 'CommentsBundle\\Entity\\comments' . "\0" . 'authoremail', '' . "\0" . 'CommentsBundle\\Entity\\comments' . "\0" . 'authorurl', '' . "\0" . 'CommentsBundle\\Entity\\comments' . "\0" . 'article_id');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (comments $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuthorName($authorname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuthorName', array($authorname));

        return parent::setAuthorName($authorname);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthorName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthorName', array());

        return parent::getAuthorName();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuthorEmail($authoremail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuthorEmail', array($authoremail));

        return parent::setAuthorEmail($authoremail);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthorEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthorEmail', array());

        return parent::getAuthorEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuthorUrl($authorurl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuthorUrl', array($authorurl));

        return parent::setAuthorUrl($authorurl);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthorUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthorUrl', array());

        return parent::getAuthorUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setArticleId($article_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArticleId', array($article_id));

        return parent::setArticleId($article_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticleId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticleId', array());

        return parent::getArticleId();
    }

}
