<?php

namespace CommentsBundle\Entity;

/**
 * commentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commentsRepository extends \Doctrine\ORM\EntityRepository
{
}
